In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("synthetic_ev_battery_health.csv")

In [5]:
dataset

,Battery_ID,Cycles,Voltage_V,Current_A,Temperature_C,Internal_Resistance_mOhm,Capacity_Ah,SOH
0,B00001,165,3.43,3.45,29.2,40.2,47.54,95.33
1,B00002,386,4.19,3.09,30.0,48.6,46.98,90.41
2,B00003,303,4.18,3.96,28.8,39.6,46.37,91.79
3,B00004,1572,4.02,1.46,22.8,92.2,33.49,69.18
4,B00005,1708,3.30,0.89,27.7,100.9,33.65,66.52
...,...,...,...,...,...,...,...,...
9995,B09996,1076,3.82,1.18,25.5,75.0,39.35,77.71
9996,B09997,398,3.80,3.36,26.0,43.0,46.16,92.31
9997,B09998,452,3.64,4.98,28.7,47.2,46.04,89.68
9998,B09999,116,4.12,3.12,27.9,30.5,48.63,96.10
9999,B10000,379,3.75,1.22,46.0,47.2,46.09,89.20

In [6]:
dataset.isnull().sum()

Battery_ID                  0
Cycles                      0
Voltage_V                   0
Current_A                   0
Temperature_C               0
Internal_Resistance_mOhm    0
Capacity_Ah                 0
SOH                         0
dtype: int64

In [7]:
dataset.describe()

,Cycles,Voltage_V,Current_A,Temperature_C,Internal_Resistance_mOhm,Capacity_Ah,SOH
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,999.763400,3.701544,2.741918,34.921090,70.022450,40.004203,78.502644
std,574.884249,0.289164,1.303848,8.631356,23.133155,5.771934,11.618488
min,0.000000,3.200000,0.500000,20.000000,25.200000,29.040000,55.100000
25%,504.000000,3.450000,1.620000,27.500000,50.300000,35.050000,68.560000
50%,999.000000,3.700000,2.750000,34.800000,69.950000,40.020000,78.540000
75%,1497.000000,3.950000,3.870000,42.300000,89.900000,44.942500,88.420000
max,2000.000000,4.200000,5.000000,50.000000,114.600000,50.940000,100.000000

### Removing unwanted columns

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Battery_ID                10000 non-null  object
 1   Cycles                    10000 non-null  int64
 2   Voltage_V                 10000 non-null  float64
 3   Current_A                 10000 non-null  float64
 4   Temperature_C             10000 non-null  float64
 5   Internal_Resistance_mOhm  10000 non-null  float64
 6   Capacity_Ah               10000 non-null  float64
 7   SOH                       10000 non-null  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 625.1+ KB

In [9]:
dataset.columns

Index(['Battery_ID', 'Cycles', 'Voltage_V', 'Current_A', 'Temperature_C',
       'Internal_Resistance_mOhm', 'Capacity_Ah', 'SOH'],
      dtype='object')

In [10]:
dataset.sample()

,Battery_ID,Cycles,Voltage_V,Current_A,Temperature_C,Internal_Resistance_mOhm,Capacity_Ah,SOH
6556,B06557,1298,3.55,3.21,24.2,80.1,37.57,73.91

In [11]:
dataset

,Battery_ID,Cycles,Voltage_V,Current_A,Temperature_C,Internal_Resistance_mOhm,Capacity_Ah,SOH
0,B00001,165,3.43,3.45,29.2,40.2,47.54,95.33
1,B00002,386,4.19,3.09,30.0,48.6,46.98,90.41
2,B00003,303,4.18,3.96,28.8,39.6,46.37,91.79
3,B00004,1572,4.02,1.46,22.8,92.2,33.49,69.18
4,B00005,1708,3.30,0.89,27.7,100.9,33.65,66.52
...,...,...,...,...,...,...,...,...
9995,B09996,1076,3.82,1.18,25.5,75.0,39.35,77.71
9996,B09997,398,3.80,3.36,26.0,43.0,46.16,92.31
9997,B09998,452,3.64,4.98,28.7,47.2,46.04,89.68
9998,B09999,116,4.12,3.12,27.9,30.5,48.63,96.10
9999,B10000,379,3.75,1.22,46.0,47.2,46.09,89.20

In [12]:
useless_col = ['Battery_ID']

In [13]:
dataset = dataset.drop(columns = useless_col, axis=1)

In [15]:
dataset.to_csv("pre_processed_synthetic_ev.csv", index=False)

In [16]:
dataset.isnull().sum()

Cycles                      0
Voltage_V                   0
Current_A                   0
Temperature_C               0
Internal_Resistance_mOhm    0
Capacity_Ah                 0
SOH                         0
dtype: int64

In [17]:
dataset.describe()

,Cycles,Voltage_V,Current_A,Temperature_C,Internal_Resistance_mOhm,Capacity_Ah,SOH
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,999.763400,3.701544,2.741918,34.921090,70.022450,40.004203,78.502644
std,574.884249,0.289164,1.303848,8.631356,23.133155,5.771934,11.618488
min,0.000000,3.200000,0.500000,20.000000,25.200000,29.040000,55.100000
25%,504.000000,3.450000,1.620000,27.500000,50.300000,35.050000,68.560000
50%,999.000000,3.700000,2.750000,34.800000,69.950000,40.020000,78.540000
75%,1497.000000,3.950000,3.870000,42.300000,89.900000,44.942500,88.420000
max,2000.000000,4.200000,5.000000,50.000000,114.600000,50.940000,100.000000