In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("cs_students.csv")

In [3]:
dataset.head()

,Student ID,Name,Gender,Age,GPA,Major,Interested Domain,Projects,Future Career,Python,SQL,Java
0,1,John Smith,Male,21,3.5,Computer Science,Artificial Intelligence,Chatbot Development,Machine Learning Researcher,Strong,Strong,Weak
1,2,Alice Johnson,Female,20,3.2,Computer Science,Data Science,Data Analytics,Data Scientist,Average,Strong,Weak
2,3,Robert Davis,Male,22,3.8,Computer Science,Software Development,E-commerce Website,Software Engineer,Strong,Strong,Average
3,4,Emily Wilson,Female,21,3.7,Computer Science,Web Development,Full-Stack Web App,Web Developer,Weak,Strong,Strong
4,5,Michael Brown,Male,23,3.4,Computer Science,Cybersecurity,Network Security,Information Security Analyst,Average,Weak,Strong

In [4]:
dataset.isnull().sum()

Student ID           0
Name                 0
Gender               0
Age                  0
GPA                  0
Major                0
Interested Domain    0
Projects             0
Future Career        0
Python               0
SQL                  0
Java                 0
dtype: int64

In [5]:
dataset.describe()

       Student ID         Age         GPA
count  180.000000  180.000000  180.000000
mean    90.500000   22.116667    3.615000
std     52.105662    2.823040    0.177341
min      1.000000   20.000000    3.200000
25%     45.750000   21.000000    3.500000
50%     90.500000   22.000000    3.600000
75%    135.250000   22.250000    3.700000
max    180.000000   37.000000    3.900000

### Removing unwanted columns

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student ID         180 non-null    int64
 1   Name               180 non-null    object
 2   Gender             180 non-null    object
 3   Age                180 non-null    int64
 4   GPA                180 non-null    float64
 5   Major              180 non-null    object
 6   Interested Domain  180 non-null    object
 7   Projects           180 non-null    object
 8   Future Career      180 non-null    object
 9   Python             180 non-null    object
 10  SQL                180 non-null    object
 11  Java               180 non-null    object
dtypes: float64(1), int64(2), object(9)
memory usage: 17.0+ KB

In [7]:
dataset.columns

Index(['Student ID', 'Name', 'Gender', 'Age', 'GPA', 'Major',
       'Interested Domain', 'Projects', 'Future Career', 'Python', 'SQL',
       'Java'],
      dtype='object')

In [8]:
dataset.sample()

,Student ID,Name,Gender,Age,GPA,Major,Interested Domain,Projects,Future Career,Python,SQL,Java
42,43,Harry Osborn,Male,23,3.5,Computer Science,Mobile App Development,iOS Game,Mobile App Developer,Average,Weak,Strong

In [9]:
dataset

,Student ID,Name,Gender,Age,GPA,Major,Interested Domain,Projects,Future Career,Python,SQL,Java
0,1,John Smith,Male,21,3.5,Computer Science,Artificial Intelligence,Chatbot Development,Machine Learning Researcher,Strong,Strong,Weak
1,2,Alice Johnson,Female,20,3.2,Computer Science,Data Science,Data Analytics,Data Scientist,Average,Strong,Weak
2,3,Robert Davis,Male,22,3.8,Computer Science,Software Development,E-commerce Website,Software Engineer,Strong,Strong,Average
3,4,Emily Wilson,Female,21,3.7,Computer Science,Web Development,Full-Stack Web App,Web Developer,Weak,Strong,Strong
4,5,Michael Brown,Male,23,3.4,Computer Science,Cybersecurity,Network Security,Information Security Analyst,Average,Weak,Strong
...,...,...,...,...,...,...,...,...,...,...,...,...
175,176,Elijah Davis,Male,22,3.7,Computer Science,Web Development,Full-Stack Web App,Web Developer,Weak,Strong,Strong
176,177,Emma Johnson,Female,20,3.6,Computer Science,Cybersecurity,Security Auditing,Information Security Analyst,Strong,Average,Weak
177,178,Liam Wilson,Male,21,3.4,Computer Science,Machine Learning,Natural Language Processing,Machine Learning Engineer,Strong,Average,Weak
178,179,Sophia Johnson,Female,22,3.5,Computer Science,Database Management,SQL Database Administration,Database Administrator,Weak,Strong,Average
179,180,Michael Brown,Male,23,3.7,Computer Science,Cloud Computing,Cloud Solution Architecture,Cloud Solutions Architect,Strong,Strong,Weak

In [10]:
useless_col = ['Student ID', 'Name', 'Major','Projects']

In [11]:
dataset = dataset.drop(columns = useless_col, axis=1)

In [12]:
dataset.to_csv("pre_processed_std.csv", index=False)

In [13]:
dataset.isnull().sum()

Gender               0
Age                  0
GPA                  0
Interested Domain    0
Future Career        0
Python               0
SQL                  0
Java                 0
dtype: int64

In [14]:
dataset.describe()

              Age         GPA
count  180.000000  180.000000
mean    22.116667    3.615000
std      2.823040    0.177341
min     20.000000    3.200000
25%     21.000000    3.500000
50%     22.000000    3.600000
75%     22.250000    3.700000
max     37.000000    3.900000