In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("cs_students.csv")

In [3]:
dataset.head()

,Student ID,Name,Gender,Age,GPA,Major,Interested Domain,Projects,Future Career,Python,SQL,Java
0,1,John Smith,Male,21,3.5,Computer Science,Artificial Intelligence,Chatbot Development,Machine Learning Researcher,Strong,Strong,Weak
1,2,Alice Johnson,Female,20,3.2,Computer Science,Data Science,Data Analytics,Data Scientist,Average,Strong,Weak
2,3,Robert Davis,Male,22,3.8,Computer Science,Software Development,E-commerce Website,Software Engineer,Strong,Strong,Average
3,4,Emily Wilson,Female,21,3.7,Computer Science,Web Development,Full-Stack Web App,Web Developer,Weak,Strong,Strong
4,5,Michael Brown,Male,23,3.4,Computer Science,Cybersecurity,Network Security,Information Security Analyst,Average,Weak,Strong

In [4]:
dataset.isnull().sum()

Student ID           0
Name                 0
Gender               0
Age                  0
GPA                  0
Major                0
Interested Domain    0
Projects             0
Future Career        0
Python               0
SQL                  0
Java                 0
dtype: int64

In [5]:
dataset.describe()

       Student ID         Age         GPA
count  180.000000  180.000000  180.000000
mean    90.500000   22.116667    3.615000
std     52.105662    2.823040    0.177341
min      1.000000   20.000000    3.200000
25%     45.750000   21.000000    3.500000
50%     90.500000   22.000000    3.600000
75%    135.250000   22.250000    3.700000
max    180.000000   37.000000    3.900000

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student ID         180 non-null    int64
 1   Name               180 non-null    object
 2   Gender             180 non-null    object
 3   Age                180 non-null    int64
 4   GPA                180 non-null    float64
 5   Major              180 non-null    object
 6   Interested Domain  180 non-null    object
 7   Projects           180 non-null    object
 8   Future Career      180 non-null    object
 9   Python             180 non-null    object
 10  SQL                180 non-null    object
 11  Java               180 non-null    object
dtypes: float64(1), int64(2), object(9)
memory usage: 17.0+ KB

In [7]:
dataset.columns

Index(['Student ID', 'Name', 'Gender', 'Age', 'GPA', 'Major',
       'Interested Domain', 'Projects', 'Future Career', 'Python', 'SQL',
       'Java'],
      dtype='object')

In [8]:
dataset.sample()

,Student ID,Name,Gender,Age,GPA,Major,Interested Domain,Projects,Future Career,Python,SQL,Java
171,172,Charlotte Davis,Female,22,3.7,Computer Science,Database Management,SQL Database Design,Database Administrator,Weak,Strong,Average

### Univariate

In [9]:
dataset['GPA'].mean()

np.float64(3.615)

In [10]:
dataset['GPA'].median()

3.6

In [11]:
dataset['Age'].mode()[0]

np.int64(22)

#### 1. Central Tendency

In [12]:
import warnings
warnings.filterwarnings('ignore')

In [13]:
col = ['Age', 'GPA']

In [14]:
col

['Age', 'GPA']

In [15]:
descriptive = pd.DataFrame(index=["Mean","Median","Mode"], columns=col)

In [16]:
descriptive

        Age  GPA
Mean    NaN  NaN
Median  NaN  NaN
Mode    NaN  NaN

In [17]:
descriptive["Age"]["Median"] = 0

In [18]:
descriptive

        Age  GPA
Mean    NaN  NaN
Median    0  NaN
Mode    NaN  NaN

In [19]:
for columnNames in dataset.columns:
    if columnNames in col:
        print(columnNames)
        descriptive[columnNames]["Mean"] = dataset[columnNames].mean()
        descriptive[columnNames]["Median"] = dataset[columnNames].median()
        descriptive[columnNames]["Mode"] = descriptive[columnNames].mode()[0]

Age
GPA

In [20]:
descriptive

              Age    GPA
Mean    22.116667  3.615
Median       22.0    3.6
Mode         22.0    3.6

#### 2.Percentile

In [21]:
descriptive = pd.DataFrame(index=["Mean","Median","Mode","25%","50%","75%","100%"],columns=col)
for columnName in col:
        descriptive[columnName]["Mean"] = dataset[columnName].mean()
        descriptive[columnName]["Median"] = dataset[columnName].median()
        descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
        descriptive[columnName]["25%"] = dataset.describe()[columnName]["25%"]
        descriptive[columnName]["50%"] = dataset.describe()[columnName]["50%"]
        descriptive[columnName]["75%"] = dataset.describe()[columnName]["75%"]
        descriptive[columnName]["100%"] = dataset.describe()[columnName]["max"]

In [22]:
descriptive

              Age    GPA
Mean    22.116667  3.615
Median       22.0    3.6
Mode           22    3.7
25%          21.0    3.5
50%          22.0    3.6
75%         22.25    3.7
100%         37.0    3.9

#### 3.1 IQR

In [23]:
descriptive = pd.DataFrame(index=["Mean","Median","Mode","25%","50%","75%","100%","IQR","1.5*IQR","Lesser","Greater","Min","Max"],columns=col)
for columnName in col:
        descriptive[columnName]["Mean"] = dataset[columnName].mean()
        descriptive[columnName]["Median"] = dataset[columnName].median()
        descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
        descriptive[columnName]["25%"] = dataset.describe()[columnName]["25%"]
        descriptive[columnName]["50%"] = dataset.describe()[columnName]["50%"]
        descriptive[columnName]["75%"] = dataset.describe()[columnName]["75%"]
        descriptive[columnName]["100%"] = dataset.describe()[columnName]["max"]
        descriptive[columnName]["IQR"] = descriptive[columnName]["75%"] - descriptive[columnName]["25%"]
        descriptive[columnName]["1.5*IQR"] = 1.5 * descriptive[columnName]["IQR"]
        descriptive[columnName]["Lesser"] = descriptive[columnName]["25%"] - descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Greater"] = descriptive[columnName]["75%"] + descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Min"] = dataset[columnName].min()
        descriptive[columnName]["Max"] = dataset[columnName].max()

In [24]:
descriptive

               Age    GPA
Mean     22.116667  3.615
Median        22.0    3.6
Mode            22    3.7
25%           21.0    3.5
50%           22.0    3.6
75%          22.25    3.7
100%          37.0    3.9
IQR           1.25    0.2
1.5*IQR      1.875    0.3
Lesser      19.125    3.2
Greater     24.125    4.0
Min             20    3.2
Max             37    3.9

#### 3.2 Finding Outlier

In [25]:
descriptive["GPA"]["Lesser"] > descriptive["GPA"]["Min"]

np.False_

In [26]:
lesser = []
greater = []
#quan = ["Age","GPA"]
for columnName in col:
    #print(col)
    if descriptive[columnName]["Lesser"] > descriptive[columnName]["Min"]:
        lesser.append(columnName)
    if descriptive[columnName]["Greater"] < descriptive[columnName]["Max"]:
        greater.append(columnName)

In [27]:
lesser

[]

In [28]:
greater

['Age']

### 3.3 Replace Outlier

In [29]:
for columnName in lesser:
    dataset[columnName][dataset[columnName]<descriptive[columnName]["Lesser"]] = descriptive[columnName]["Lesser"]
for columnName in greater:
    dataset[columnName][dataset[columnName]>descriptive[columnName]["Greater"]] = descriptive[columnName]["Greater"]

In [30]:
descriptive = pd.DataFrame(index=["Mean","Median","Mode","25%","50%","75%","100%","IQR","1.5*IQR","Lesser","Greater","Min","Max"],columns=col)
for columnName in col:
        descriptive[columnName]["Mean"] = dataset[columnName].mean()
        descriptive[columnName]["Median"] = dataset[columnName].median()
        descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
        descriptive[columnName]["25%"] = dataset.describe()[columnName]["25%"]
        descriptive[columnName]["50%"] = dataset.describe()[columnName]["50%"]
        descriptive[columnName]["75%"] = dataset.describe()[columnName]["75%"]
        descriptive[columnName]["100%"] = dataset.describe()[columnName]["max"]
        descriptive[columnName]["IQR"] = descriptive[columnName]["75%"] - descriptive[columnName]["25%"]
        descriptive[columnName]["1.5*IQR"] = 1.5 * descriptive[columnName]["IQR"]
        descriptive[columnName]["Lesser"] = descriptive[columnName]["25%"] - descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Greater"] = descriptive[columnName]["75%"] + descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Min"] = dataset[columnName].min()
        descriptive[columnName]["Max"] = dataset[columnName].max()

In [31]:
lesser=[]
greater=[]
for columnName in col:
    if descriptive[columnName]["Lesser"] > descriptive[columnName]["Min"]:
        lesser.append(columnName)
    if descriptive[columnName]["Greater"] < descriptive[columnName]["100%"]:
        greater.append(columnName)

In [32]:
lesser

[]

In [33]:
greater

[]

In [34]:
descriptive

               Age    GPA
Mean     21.661806  3.615
Median        22.0    3.6
Mode          22.0    3.7
25%           21.0    3.5
50%           22.0    3.6
75%          22.25    3.7
100%        24.125    3.9
IQR           1.25    0.2
1.5*IQR      1.875    0.3
Lesser      19.125    3.2
Greater     24.125    4.0
Min           20.0    3.2
Max         24.125    3.9

### 4. Frequency

In [35]:
dataset["GPA"].value_counts()

GPA
3.7    44
3.5    33
3.8    31
3.6    29
3.3    21
3.9    13
3.4     7
3.2     2
Name: count, dtype: int64

In [36]:
freqTable = pd.DataFrame(columns=["UniqueValues","Frequency","Relative_Frequency","Cumsum"])
freqTable

Empty DataFrame
Columns: [UniqueValues, Frequency, Relative_Frequency, Cumsum]
Index: []

In [37]:
freqTable["UniqueValues"] = dataset["GPA"].value_counts().index
freqTable["Frequency"] = dataset["GPA"].value_counts().values
freqTable["Relative_Frequency"] = freqTable["Frequency"]/91
freqTable["Cumsum"] = freqTable["Relative_Frequency"].cumsum()

In [38]:
def freqTable(columnName, dataset):
    freqTable = pd.DataFrame(columns=["UniqueValues","Frequency","Relative_Frequency","Cumsum"])
    freqTable["UniqueValues"] = dataset[columnName].value_counts().index
    freqTable["Frequency"] = dataset[columnName].value_counts().values
    freqTable["Relative_Frequency"] = freqTable["Frequency"]/91
    freqTable["Cumsum"] = freqTable["Relative_Frequency"].cumsum()
    return freqTable

In [39]:
def Univariate(dataset,col):
    descriptive = pd.DataFrame(index=["Mean","Median","Mode","25%","50%","75%","100%","IQR","1.5*IQR","Lesser","Greater","Min","Max"],columns=col)
    for columnName in col:
        descriptive[columnName]["Mean"] = dataset[columnName].mean()
        descriptive[columnName]["Median"] = dataset[columnName].median()
        descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
        descriptive[columnName]["25%"] = dataset.describe()[columnName]["25%"]
        descriptive[columnName]["50%"] = dataset.describe()[columnName]["50%"]
        descriptive[columnName]["75%"] = dataset.describe()[columnName]["75%"]
        descriptive[columnName]["100%"] = dataset.describe()[columnName]["max"]
        descriptive[columnName]["IQR"] = descriptive[columnName]["75%"] - descriptive[columnName]["25%"]
        descriptive[columnName]["1.5*IQR"] = 1.5 * descriptive[columnName]["IQR"]
        descriptive[columnName]["Lesser"] = descriptive[columnName]["25%"] - descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Greater"] = descriptive[columnName]["75%"] + descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Min"] = dataset[columnName].min()
        descriptive[columnName]["Max"] = dataset[columnName].max()
    return descriptive

In [40]:
col

['Age', 'GPA']

In [41]:
dataset

,Student ID,Name,Gender,Age,GPA,Major,Interested Domain,Projects,Future Career,Python,SQL,Java
0,1,John Smith,Male,21.0,3.5,Computer Science,Artificial Intelligence,Chatbot Development,Machine Learning Researcher,Strong,Strong,Weak
1,2,Alice Johnson,Female,20.0,3.2,Computer Science,Data Science,Data Analytics,Data Scientist,Average,Strong,Weak
2,3,Robert Davis,Male,22.0,3.8,Computer Science,Software Development,E-commerce Website,Software Engineer,Strong,Strong,Average
3,4,Emily Wilson,Female,21.0,3.7,Computer Science,Web Development,Full-Stack Web App,Web Developer,Weak,Strong,Strong
4,5,Michael Brown,Male,23.0,3.4,Computer Science,Cybersecurity,Network Security,Information Security Analyst,Average,Weak,Strong
...,...,...,...,...,...,...,...,...,...,...,...,...
175,176,Elijah Davis,Male,22.0,3.7,Computer Science,Web Development,Full-Stack Web App,Web Developer,Weak,Strong,Strong
176,177,Emma Johnson,Female,20.0,3.6,Computer Science,Cybersecurity,Security Auditing,Information Security Analyst,Strong,Average,Weak
177,178,Liam Wilson,Male,21.0,3.4,Computer Science,Machine Learning,Natural Language Processing,Machine Learning Engineer,Strong,Average,Weak
178,179,Sophia Johnson,Female,22.0,3.5,Computer Science,Database Management,SQL Database Administration,Database Administrator,Weak,Strong,Average
179,180,Michael Brown,Male,23.0,3.7,Computer Science,Cloud Computing,Cloud Solution Architecture,Cloud Solutions Architect,Strong,Strong,Weak

In [42]:
Univariate(dataset,col)

               Age    GPA
Mean     21.661806  3.615
Median        22.0    3.6
Mode          22.0    3.7
25%           21.0    3.5
50%           22.0    3.6
75%          22.25    3.7
100%        24.125    3.9
IQR           1.25    0.2
1.5*IQR      1.875    0.3
Lesser      19.125    3.2
Greater     24.125    4.0
Min           20.0    3.2
Max         24.125    3.9

In [43]:
dataset["GPA"].value_counts()

GPA
3.7    44
3.5    33
3.8    31
3.6    29
3.3    21
3.9    13
3.4     7
3.2     2
Name: count, dtype: int64

### 5.HSK

In [44]:
dataset["GPA"].skew()

np.float64(-0.4000367650563136)

In [45]:
dataset["GPA"].kurtosis()

np.float64(-0.6492870035721889)

In [46]:
def Univariate(dataset,quan):
    descriptive = pd.DataFrame(index=["Mean","Median","Mode","25%","50%","75%","100%","IQR","1.5*IQR","Lesser","Greater","Min","Max","Skewness","Kurtosis"],columns=col)
    for columnName in col:
        descriptive[columnName]["Mean"] = dataset[columnName].mean()
        descriptive[columnName]["Median"] = dataset[columnName].median()
        descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
        descriptive[columnName]["25%"] = dataset.describe()[columnName]["25%"]
        descriptive[columnName]["50%"] = dataset.describe()[columnName]["50%"]
        descriptive[columnName]["75%"] = dataset.describe()[columnName]["75%"]
        descriptive[columnName]["100%"] = dataset.describe()[columnName]["max"]
        descriptive[columnName]["IQR"] = descriptive[columnName]["75%"] - descriptive[columnName]["25%"]
        descriptive[columnName]["1.5*IQR"] = 1.5 * descriptive[columnName]["IQR"]
        descriptive[columnName]["Lesser"] = descriptive[columnName]["25%"] - descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Greater"] = descriptive[columnName]["75%"] + descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Min"] = dataset[columnName].min()
        descriptive[columnName]["Max"] = dataset[columnName].max()
        descriptive[columnName]["Skewness"] = dataset[columnName].skew()
        descriptive[columnName]["Kurtosis"] = dataset[columnName].kurtosis()
    return descriptive

In [47]:
Univariate(dataset,col)

                Age       GPA
Mean      21.661806     3.615
Median         22.0       3.6
Mode           22.0       3.7
25%            21.0       3.5
50%            22.0       3.6
75%           22.25       3.7
100%         24.125       3.9
IQR            1.25       0.2
1.5*IQR       1.875       0.3
Lesser       19.125       3.2
Greater      24.125       4.0
Min            20.0       3.2
Max          24.125       3.9
Skewness    0.19235 -0.400037
Kurtosis  -0.751175 -0.649287

In [48]:
### 6. Data-Preprocessing

In [49]:
dataset

,Student ID,Name,Gender,Age,GPA,Major,Interested Domain,Projects,Future Career,Python,SQL,Java
0,1,John Smith,Male,21.0,3.5,Computer Science,Artificial Intelligence,Chatbot Development,Machine Learning Researcher,Strong,Strong,Weak
1,2,Alice Johnson,Female,20.0,3.2,Computer Science,Data Science,Data Analytics,Data Scientist,Average,Strong,Weak
2,3,Robert Davis,Male,22.0,3.8,Computer Science,Software Development,E-commerce Website,Software Engineer,Strong,Strong,Average
3,4,Emily Wilson,Female,21.0,3.7,Computer Science,Web Development,Full-Stack Web App,Web Developer,Weak,Strong,Strong
4,5,Michael Brown,Male,23.0,3.4,Computer Science,Cybersecurity,Network Security,Information Security Analyst,Average,Weak,Strong
...,...,...,...,...,...,...,...,...,...,...,...,...
175,176,Elijah Davis,Male,22.0,3.7,Computer Science,Web Development,Full-Stack Web App,Web Developer,Weak,Strong,Strong
176,177,Emma Johnson,Female,20.0,3.6,Computer Science,Cybersecurity,Security Auditing,Information Security Analyst,Strong,Average,Weak
177,178,Liam Wilson,Male,21.0,3.4,Computer Science,Machine Learning,Natural Language Processing,Machine Learning Engineer,Strong,Average,Weak
178,179,Sophia Johnson,Female,22.0,3.5,Computer Science,Database Management,SQL Database Administration,Database Administrator,Weak,Strong,Average
179,180,Michael Brown,Male,23.0,3.7,Computer Science,Cloud Computing,Cloud Solution Architecture,Cloud Solutions Architect,Strong,Strong,Weak

In [50]:
dataset.isnull().sum()

Student ID           0
Name                 0
Gender               0
Age                  0
GPA                  0
Major                0
Interested Domain    0
Projects             0
Future Career        0
Python               0
SQL                  0
Java                 0
dtype: int64

In [51]:
dataset["GPA"].fillna(0,inplace=True)

In [52]:
dataset

,Student ID,Name,Gender,Age,GPA,Major,Interested Domain,Projects,Future Career,Python,SQL,Java
0,1,John Smith,Male,21.0,3.5,Computer Science,Artificial Intelligence,Chatbot Development,Machine Learning Researcher,Strong,Strong,Weak
1,2,Alice Johnson,Female,20.0,3.2,Computer Science,Data Science,Data Analytics,Data Scientist,Average,Strong,Weak
2,3,Robert Davis,Male,22.0,3.8,Computer Science,Software Development,E-commerce Website,Software Engineer,Strong,Strong,Average
3,4,Emily Wilson,Female,21.0,3.7,Computer Science,Web Development,Full-Stack Web App,Web Developer,Weak,Strong,Strong
4,5,Michael Brown,Male,23.0,3.4,Computer Science,Cybersecurity,Network Security,Information Security Analyst,Average,Weak,Strong
...,...,...,...,...,...,...,...,...,...,...,...,...
175,176,Elijah Davis,Male,22.0,3.7,Computer Science,Web Development,Full-Stack Web App,Web Developer,Weak,Strong,Strong
176,177,Emma Johnson,Female,20.0,3.6,Computer Science,Cybersecurity,Security Auditing,Information Security Analyst,Strong,Average,Weak
177,178,Liam Wilson,Male,21.0,3.4,Computer Science,Machine Learning,Natural Language Processing,Machine Learning Engineer,Strong,Average,Weak
178,179,Sophia Johnson,Female,22.0,3.5,Computer Science,Database Management,SQL Database Administration,Database Administrator,Weak,Strong,Average
179,180,Michael Brown,Male,23.0,3.7,Computer Science,Cloud Computing,Cloud Solution Architecture,Cloud Solutions Architect,Strong,Strong,Weak

In [53]:
dataset.isna().sum()

Student ID           0
Name                 0
Gender               0
Age                  0
GPA                  0
Major                0
Interested Domain    0
Projects             0
Future Career        0
Python               0
SQL                  0
Java                 0
dtype: int64

In [54]:
# Other method
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy="mean")
imp.fit(dataset[col])
df=imp.transform(dataset[col])
df = pd.DataFrame(df, columns = col)

In [55]:
df

      Age  GPA
0    21.0  3.5
1    20.0  3.2
2    22.0  3.8
3    21.0  3.7
4    23.0  3.4
..    ...  ...
175  22.0  3.7
176  20.0  3.6
177  21.0  3.4
178  22.0  3.5
179  23.0  3.7

[180 rows x 2 columns]

In [56]:
# Variance and STD

In [57]:
def Univariate(dataset,col):
    descriptive = pd.DataFrame(index=["Mean","Median","Mode","25%","50%","75%","100%","IQR","1.5*IQR","Lesser","Greater","Min",
                                      "Max","Skewness","Kurtosis","Variance","Std"],columns=col)
    for columnName in col:
        descriptive[columnName]["Mean"] = dataset[columnName].mean()
        descriptive[columnName]["Median"] = dataset[columnName].median()
        descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
        descriptive[columnName]["25%"] = dataset.describe()[columnName]["25%"]
        descriptive[columnName]["50%"] = dataset.describe()[columnName]["50%"]
        descriptive[columnName]["75%"] = dataset.describe()[columnName]["75%"]
        descriptive[columnName]["100%"] = dataset.describe()[columnName]["max"]
        descriptive[columnName]["IQR"] = descriptive[columnName]["75%"] - descriptive[columnName]["25%"]
        descriptive[columnName]["1.5*IQR"] = 1.5 * descriptive[columnName]["IQR"]
        descriptive[columnName]["Lesser"] = descriptive[columnName]["25%"] - descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Greater"] = descriptive[columnName]["75%"] + descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Min"] = dataset[columnName].min()
        descriptive[columnName]["Max"] = dataset[columnName].max()
        descriptive[columnName]["Skewness"] = dataset[columnName].skew()
        descriptive[columnName]["Kurtosis"] = dataset[columnName].kurtosis()
        descriptive[columnName]["Variance"] = dataset[columnName].var()
        descriptive[columnName]["Std"] = dataset[columnName].std()
    return descriptive

In [58]:
Univariate(dataset,col)

                Age       GPA
Mean      21.661806     3.615
Median         22.0       3.6
Mode           22.0       3.7
25%            21.0       3.5
50%            22.0       3.6
75%           22.25       3.7
100%         24.125       3.9
IQR            1.25       0.2
1.5*IQR       1.875       0.3
Lesser       19.125       3.2
Greater      24.125       4.0
Min            20.0       3.2
Max          24.125       3.9
Skewness    0.19235 -0.400037
Kurtosis  -0.751175 -0.649287
Variance   1.341078   0.03145
Std        1.158049  0.177341

In [59]:
df

      Age  GPA
0    21.0  3.5
1    20.0  3.2
2    22.0  3.8
3    21.0  3.7
4    23.0  3.4
..    ...  ...
175  22.0  3.7
176  20.0  3.6
177  21.0  3.4
178  22.0  3.5
179  23.0  3.7

[180 rows x 2 columns]

In [60]:
cate = pd.DataFrame(dataset,columns=col)

In [61]:
cate

      Age  GPA
0    21.0  3.5
1    20.0  3.2
2    22.0  3.8
3    21.0  3.7
4    23.0  3.4
..    ...  ...
175  22.0  3.7
176  20.0  3.6
177  21.0  3.4
178  22.0  3.5
179  23.0  3.7

[180 rows x 2 columns]

In [62]:
two = [df,cate]
preprocessed = pd.concat(two,axis=0)

In [63]:
preprocessed

      Age  GPA
0    21.0  3.5
1    20.0  3.2
2    22.0  3.8
3    21.0  3.7
4    23.0  3.4
..    ...  ...
175  22.0  3.7
176  20.0  3.6
177  21.0  3.4
178  22.0  3.5
179  23.0  3.7

[360 rows x 2 columns]