In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset = pd.read_csv("pre_processed_synthetic_ev.csv")

In [3]:
dataset.head()

,Cycles,Voltage_V,Current_A,Temperature_C,Internal_Resistance_mOhm,Capacity_Ah,SOH
0,165,3.43,3.45,29.2,40.2,47.54,95.33
1,386,4.19,3.09,30.0,48.6,46.98,90.41
2,303,4.18,3.96,28.8,39.6,46.37,91.79
3,1572,4.02,1.46,22.8,92.2,33.49,69.18
4,1708,3.30,0.89,27.7,100.9,33.65,66.52

In [4]:
dataset.isnull().sum()

Cycles                      0
Voltage_V                   0
Current_A                   0
Temperature_C               0
Internal_Resistance_mOhm    0
Capacity_Ah                 0
SOH                         0
dtype: int64

In [5]:
dataset.describe()

,Cycles,Voltage_V,Current_A,Temperature_C,Internal_Resistance_mOhm,Capacity_Ah,SOH
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,999.763400,3.701544,2.741918,34.921090,70.022450,40.004203,78.502644
std,574.884249,0.289164,1.303848,8.631356,23.133155,5.771934,11.618488
min,0.000000,3.200000,0.500000,20.000000,25.200000,29.040000,55.100000
25%,504.000000,3.450000,1.620000,27.500000,50.300000,35.050000,68.560000
50%,999.000000,3.700000,2.750000,34.800000,69.950000,40.020000,78.540000
75%,1497.000000,3.950000,3.870000,42.300000,89.900000,44.942500,88.420000
max,2000.000000,4.200000,5.000000,50.000000,114.600000,50.940000,100.000000

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Cycles                    10000 non-null  int64
 1   Voltage_V                 10000 non-null  float64
 2   Current_A                 10000 non-null  float64
 3   Temperature_C             10000 non-null  float64
 4   Internal_Resistance_mOhm  10000 non-null  float64
 5   Capacity_Ah               10000 non-null  float64
 6   SOH                       10000 non-null  float64
dtypes: float64(6), int64(1)
memory usage: 547.0 KB

In [7]:
dataset.columns

Index(['Cycles', 'Voltage_V', 'Current_A', 'Temperature_C',
       'Internal_Resistance_mOhm', 'Capacity_Ah', 'SOH'],
      dtype='object')

In [8]:
dataset.sample()

,Cycles,Voltage_V,Current_A,Temperature_C,Internal_Resistance_mOhm,Capacity_Ah,SOH
1153,673,3.3,4.77,41.0,61.6,43.11,83.43

### Univariate

In [9]:
dataset['Cycles'].mean()

np.float64(999.7634)

In [10]:
dataset['Cycles'].median()

999.0

In [11]:
dataset['Cycles'].mode()[0]

np.int64(63)

#### 1. Central Tendency

In [12]:
import warnings
warnings.filterwarnings('ignore')

In [13]:
col = ['Cycles', 'Capacity_Ah']

In [14]:
col

['Cycles', 'Capacity_Ah']

In [15]:
descriptive = pd.DataFrame(index=["Mean","Median","Mode"], columns=col)

In [16]:
descriptive

       Cycles Capacity_Ah
Mean      NaN         NaN
Median    NaN         NaN
Mode      NaN         NaN

In [17]:
descriptive["Cycles"]["Median"] = 0

In [18]:
descriptive

       Cycles Capacity_Ah
Mean      NaN         NaN
Median      0         NaN
Mode      NaN         NaN

In [19]:
for columnNames in dataset.columns:
    if columnNames in col:
        print(columnNames)
        descriptive[columnNames]["Mean"] = dataset[columnNames].mean()
        descriptive[columnNames]["Median"] = dataset[columnNames].median()
        descriptive[columnNames]["Mode"] = descriptive[columnNames].mode()[0]

Cycles
Capacity_Ah

In [20]:
descriptive

          Cycles Capacity_Ah
Mean    999.7634   40.004203
Median     999.0       40.02
Mode       999.0   40.004203

#### 2.Percentile

In [21]:
descriptive = pd.DataFrame(index=["Mean","Median","Mode","25%","50%","75%","100%"],columns=col)
for columnName in col:
        descriptive[columnName]["Mean"] = dataset[columnName].mean()
        descriptive[columnName]["Median"] = dataset[columnName].median()
        descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
        descriptive[columnName]["25%"] = dataset.describe()[columnName]["25%"]
        descriptive[columnName]["50%"] = dataset.describe()[columnName]["50%"]
        descriptive[columnName]["75%"] = dataset.describe()[columnName]["75%"]
        descriptive[columnName]["100%"] = dataset.describe()[columnName]["max"]

In [22]:
descriptive

          Cycles Capacity_Ah
Mean    999.7634   40.004203
Median     999.0       40.02
Mode          63       33.24
25%        504.0       35.05
50%        999.0       40.02
75%       1497.0     44.9425
100%      2000.0       50.94

#### 3.1 IQR

In [23]:
descriptive = pd.DataFrame(index=["Mean","Median","Mode","25%","50%","75%","100%","IQR","1.5*IQR","Lesser","Greater","Min","Max"],columns=col)
for columnName in col:
        descriptive[columnName]["Mean"] = dataset[columnName].mean()
        descriptive[columnName]["Median"] = dataset[columnName].median()
        descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
        descriptive[columnName]["25%"] = dataset.describe()[columnName]["25%"]
        descriptive[columnName]["50%"] = dataset.describe()[columnName]["50%"]
        descriptive[columnName]["75%"] = dataset.describe()[columnName]["75%"]
        descriptive[columnName]["100%"] = dataset.describe()[columnName]["max"]
        descriptive[columnName]["IQR"] = descriptive[columnName]["75%"] - descriptive[columnName]["25%"]
        descriptive[columnName]["1.5*IQR"] = 1.5 * descriptive[columnName]["IQR"]
        descriptive[columnName]["Lesser"] = descriptive[columnName]["25%"] - descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Greater"] = descriptive[columnName]["75%"] + descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Min"] = dataset[columnName].min()
        descriptive[columnName]["Max"] = dataset[columnName].max()

In [24]:
descriptive

           Cycles Capacity_Ah
Mean     999.7634   40.004203
Median      999.0       40.02
Mode           63       33.24
25%         504.0       35.05
50%         999.0       40.02
75%        1497.0     44.9425
100%       2000.0       50.94
IQR         993.0      9.8925
1.5*IQR    1489.5    14.83875
Lesser     -985.5    20.21125
Greater    2986.5    59.78125
Min             0       29.04
Max          2000       50.94

#### 3.2 Finding Outlier

In [25]:
descriptive["Cycles"]["Lesser"] > descriptive["Cycles"]["Min"]

np.False_

In [26]:
lesser = []
greater = []
#quan = ["Age","GPA"]
for columnName in col:
    #print(col)
    if descriptive[columnName]["Lesser"] > descriptive[columnName]["Min"]:
        lesser.append(columnName)
    if descriptive[columnName]["Greater"] < descriptive[columnName]["Max"]:
        greater.append(columnName)

In [27]:
lesser

[]

In [28]:
greater

[]

### 3.3 Replace Outlier

In [29]:
for columnName in lesser:
    dataset[columnName][dataset[columnName]<descriptive[columnName]["Lesser"]] = descriptive[columnName]["Lesser"]
for columnName in greater:
    dataset[columnName][dataset[columnName]>descriptive[columnName]["Greater"]] = descriptive[columnName]["Greater"]

In [30]:
descriptive = pd.DataFrame(index=["Mean","Median","Mode","25%","50%","75%","100%","IQR","1.5*IQR","Lesser","Greater","Min","Max"],columns=col)
for columnName in col:
        descriptive[columnName]["Mean"] = dataset[columnName].mean()
        descriptive[columnName]["Median"] = dataset[columnName].median()
        descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
        descriptive[columnName]["25%"] = dataset.describe()[columnName]["25%"]
        descriptive[columnName]["50%"] = dataset.describe()[columnName]["50%"]
        descriptive[columnName]["75%"] = dataset.describe()[columnName]["75%"]
        descriptive[columnName]["100%"] = dataset.describe()[columnName]["max"]
        descriptive[columnName]["IQR"] = descriptive[columnName]["75%"] - descriptive[columnName]["25%"]
        descriptive[columnName]["1.5*IQR"] = 1.5 * descriptive[columnName]["IQR"]
        descriptive[columnName]["Lesser"] = descriptive[columnName]["25%"] - descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Greater"] = descriptive[columnName]["75%"] + descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Min"] = dataset[columnName].min()
        descriptive[columnName]["Max"] = dataset[columnName].max()

In [31]:
lesser=[]
greater=[]
for columnName in col:
    if descriptive[columnName]["Lesser"] > descriptive[columnName]["Min"]:
        lesser.append(columnName)
    if descriptive[columnName]["Greater"] < descriptive[columnName]["100%"]:
        greater.append(columnName)

In [32]:
lesser

[]

In [33]:
greater

[]

In [34]:
descriptive

           Cycles Capacity_Ah
Mean     999.7634   40.004203
Median      999.0       40.02
Mode           63       33.24
25%         504.0       35.05
50%         999.0       40.02
75%        1497.0     44.9425
100%       2000.0       50.94
IQR         993.0      9.8925
1.5*IQR    1489.5    14.83875
Lesser     -985.5    20.21125
Greater    2986.5    59.78125
Min             0       29.04
Max          2000       50.94

### 4. Frequency

In [35]:
dataset["Cycles"].value_counts()

Cycles
63      16
1005    16
467     14
712     13
1945    13
        ..
824      1
875      1
1185     1
1893     1
326      1
Name: count, Length: 1992, dtype: int64

In [36]:
freqTable = pd.DataFrame(columns=["UniqueValues","Frequency","Relative_Frequency","Cumsum"])
freqTable

Empty DataFrame
Columns: [UniqueValues, Frequency, Relative_Frequency, Cumsum]
Index: []

In [37]:
freqTable["UniqueValues"] = dataset["Cycles"].value_counts().index
freqTable["Frequency"] = dataset["Cycles"].value_counts().values
freqTable["Relative_Frequency"] = freqTable["Frequency"]/91
freqTable["Cumsum"] = freqTable["Relative_Frequency"].cumsum()

In [38]:
def freqTable(columnName, dataset):
    freqTable = pd.DataFrame(columns=["UniqueValues","Frequency","Relative_Frequency","Cumsum"])
    freqTable["UniqueValues"] = dataset[columnName].value_counts().index
    freqTable["Frequency"] = dataset[columnName].value_counts().values
    freqTable["Relative_Frequency"] = freqTable["Frequency"]/91
    freqTable["Cumsum"] = freqTable["Relative_Frequency"].cumsum()
    return freqTable

In [39]:
def Univariate(dataset,col):
    descriptive = pd.DataFrame(index=["Mean","Median","Mode","25%","50%","75%","100%","IQR","1.5*IQR","Lesser","Greater","Min","Max"],columns=col)
    for columnName in col:
        descriptive[columnName]["Mean"] = dataset[columnName].mean()
        descriptive[columnName]["Median"] = dataset[columnName].median()
        descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
        descriptive[columnName]["25%"] = dataset.describe()[columnName]["25%"]
        descriptive[columnName]["50%"] = dataset.describe()[columnName]["50%"]
        descriptive[columnName]["75%"] = dataset.describe()[columnName]["75%"]
        descriptive[columnName]["100%"] = dataset.describe()[columnName]["max"]
        descriptive[columnName]["IQR"] = descriptive[columnName]["75%"] - descriptive[columnName]["25%"]
        descriptive[columnName]["1.5*IQR"] = 1.5 * descriptive[columnName]["IQR"]
        descriptive[columnName]["Lesser"] = descriptive[columnName]["25%"] - descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Greater"] = descriptive[columnName]["75%"] + descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Min"] = dataset[columnName].min()
        descriptive[columnName]["Max"] = dataset[columnName].max()
    return descriptive

In [40]:
col

['Cycles', 'Capacity_Ah']

In [41]:
dataset

,Cycles,Voltage_V,Current_A,Temperature_C,Internal_Resistance_mOhm,Capacity_Ah,SOH
0,165,3.43,3.45,29.2,40.2,47.54,95.33
1,386,4.19,3.09,30.0,48.6,46.98,90.41
2,303,4.18,3.96,28.8,39.6,46.37,91.79
3,1572,4.02,1.46,22.8,92.2,33.49,69.18
4,1708,3.30,0.89,27.7,100.9,33.65,66.52
...,...,...,...,...,...,...,...
9995,1076,3.82,1.18,25.5,75.0,39.35,77.71
9996,398,3.80,3.36,26.0,43.0,46.16,92.31
9997,452,3.64,4.98,28.7,47.2,46.04,89.68
9998,116,4.12,3.12,27.9,30.5,48.63,96.10
9999,379,3.75,1.22,46.0,47.2,46.09,89.20

In [42]:
Univariate(dataset,col)

           Cycles Capacity_Ah
Mean     999.7634   40.004203
Median      999.0       40.02
Mode           63       33.24
25%         504.0       35.05
50%         999.0       40.02
75%        1497.0     44.9425
100%       2000.0       50.94
IQR         993.0      9.8925
1.5*IQR    1489.5    14.83875
Lesser     -985.5    20.21125
Greater    2986.5    59.78125
Min             0       29.04
Max          2000       50.94

In [43]:
dataset["Cycles"].value_counts()

Cycles
63      16
1005    16
467     14
712     13
1945    13
        ..
824      1
875      1
1185     1
1893     1
326      1
Name: count, Length: 1992, dtype: int64

### 5.HSK

In [44]:
dataset["Cycles"].skew()

np.float64(-0.00017373797509249121)

In [45]:
dataset["Cycles"].kurtosis()

np.float64(-1.1902781433908722)

In [46]:
def Univariate(dataset,quan):
    descriptive = pd.DataFrame(index=["Mean","Median","Mode","25%","50%","75%","100%","IQR","1.5*IQR","Lesser","Greater","Min","Max","Skewness","Kurtosis"],columns=col)
    for columnName in col:
        descriptive[columnName]["Mean"] = dataset[columnName].mean()
        descriptive[columnName]["Median"] = dataset[columnName].median()
        descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
        descriptive[columnName]["25%"] = dataset.describe()[columnName]["25%"]
        descriptive[columnName]["50%"] = dataset.describe()[columnName]["50%"]
        descriptive[columnName]["75%"] = dataset.describe()[columnName]["75%"]
        descriptive[columnName]["100%"] = dataset.describe()[columnName]["max"]
        descriptive[columnName]["IQR"] = descriptive[columnName]["75%"] - descriptive[columnName]["25%"]
        descriptive[columnName]["1.5*IQR"] = 1.5 * descriptive[columnName]["IQR"]
        descriptive[columnName]["Lesser"] = descriptive[columnName]["25%"] - descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Greater"] = descriptive[columnName]["75%"] + descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Min"] = dataset[columnName].min()
        descriptive[columnName]["Max"] = dataset[columnName].max()
        descriptive[columnName]["Skewness"] = dataset[columnName].skew()
        descriptive[columnName]["Kurtosis"] = dataset[columnName].kurtosis()
    return descriptive

In [47]:
Univariate(dataset,col)

            Cycles Capacity_Ah
Mean      999.7634   40.004203
Median       999.0       40.02
Mode            63       33.24
25%          504.0       35.05
50%          999.0       40.02
75%         1497.0     44.9425
100%        2000.0       50.94
IQR          993.0      9.8925
1.5*IQR     1489.5    14.83875
Lesser      -985.5    20.21125
Greater     2986.5    59.78125
Min              0       29.04
Max           2000       50.94
Skewness -0.000174    0.002728
Kurtosis -1.190278    -1.16149

In [48]:
### 6. Data-Preprocessing

In [49]:
dataset

,Cycles,Voltage_V,Current_A,Temperature_C,Internal_Resistance_mOhm,Capacity_Ah,SOH
0,165,3.43,3.45,29.2,40.2,47.54,95.33
1,386,4.19,3.09,30.0,48.6,46.98,90.41
2,303,4.18,3.96,28.8,39.6,46.37,91.79
3,1572,4.02,1.46,22.8,92.2,33.49,69.18
4,1708,3.30,0.89,27.7,100.9,33.65,66.52
...,...,...,...,...,...,...,...
9995,1076,3.82,1.18,25.5,75.0,39.35,77.71
9996,398,3.80,3.36,26.0,43.0,46.16,92.31
9997,452,3.64,4.98,28.7,47.2,46.04,89.68
9998,116,4.12,3.12,27.9,30.5,48.63,96.10
9999,379,3.75,1.22,46.0,47.2,46.09,89.20

In [50]:
dataset.isnull().sum()

Cycles                      0
Voltage_V                   0
Current_A                   0
Temperature_C               0
Internal_Resistance_mOhm    0
Capacity_Ah                 0
SOH                         0
dtype: int64

In [51]:
dataset["Cycles"].fillna(0,inplace=True)

In [52]:
dataset

,Cycles,Voltage_V,Current_A,Temperature_C,Internal_Resistance_mOhm,Capacity_Ah,SOH
0,165,3.43,3.45,29.2,40.2,47.54,95.33
1,386,4.19,3.09,30.0,48.6,46.98,90.41
2,303,4.18,3.96,28.8,39.6,46.37,91.79
3,1572,4.02,1.46,22.8,92.2,33.49,69.18
4,1708,3.30,0.89,27.7,100.9,33.65,66.52
...,...,...,...,...,...,...,...
9995,1076,3.82,1.18,25.5,75.0,39.35,77.71
9996,398,3.80,3.36,26.0,43.0,46.16,92.31
9997,452,3.64,4.98,28.7,47.2,46.04,89.68
9998,116,4.12,3.12,27.9,30.5,48.63,96.10
9999,379,3.75,1.22,46.0,47.2,46.09,89.20

In [53]:
dataset.isna().sum()

Cycles                      0
Voltage_V                   0
Current_A                   0
Temperature_C               0
Internal_Resistance_mOhm    0
Capacity_Ah                 0
SOH                         0
dtype: int64

In [54]:
# Variance and STD

In [55]:
def Univariate(dataset,col):
    descriptive = pd.DataFrame(index=["Mean","Median","Mode","25%","50%","75%","100%","IQR","1.5*IQR","Lesser","Greater","Min",
                                      "Max","Skewness","Kurtosis","Variance","Std"],columns=col)
    for columnName in col:
        descriptive[columnName]["Mean"] = dataset[columnName].mean()
        descriptive[columnName]["Median"] = dataset[columnName].median()
        descriptive[columnName]["Mode"] = dataset[columnName].mode()[0]
        descriptive[columnName]["25%"] = dataset.describe()[columnName]["25%"]
        descriptive[columnName]["50%"] = dataset.describe()[columnName]["50%"]
        descriptive[columnName]["75%"] = dataset.describe()[columnName]["75%"]
        descriptive[columnName]["100%"] = dataset.describe()[columnName]["max"]
        descriptive[columnName]["IQR"] = descriptive[columnName]["75%"] - descriptive[columnName]["25%"]
        descriptive[columnName]["1.5*IQR"] = 1.5 * descriptive[columnName]["IQR"]
        descriptive[columnName]["Lesser"] = descriptive[columnName]["25%"] - descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Greater"] = descriptive[columnName]["75%"] + descriptive[columnName]["1.5*IQR"]
        descriptive[columnName]["Min"] = dataset[columnName].min()
        descriptive[columnName]["Max"] = dataset[columnName].max()
        descriptive[columnName]["Skewness"] = dataset[columnName].skew()
        descriptive[columnName]["Kurtosis"] = dataset[columnName].kurtosis()
        descriptive[columnName]["Variance"] = dataset[columnName].var()
        descriptive[columnName]["Std"] = dataset[columnName].std()
    return descriptive

In [56]:
Univariate(dataset,col)

                Cycles Capacity_Ah
Mean          999.7634   40.004203
Median           999.0       40.02
Mode                63       33.24
25%              504.0       35.05
50%              999.0       40.02
75%             1497.0     44.9425
100%            2000.0       50.94
IQR              993.0      9.8925
1.5*IQR         1489.5    14.83875
Lesser          -985.5    20.21125
Greater         2986.5    59.78125
Min                  0       29.04
Max               2000       50.94
Skewness     -0.000174    0.002728
Kurtosis     -1.190278    -1.16149
Variance  330491.90001   33.315221
Std         574.884249    5.771934